# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance <- function(lon1, lat1, lon2, lat2) {
    .Call('_vegdistmod_distance', PACKAGE = 'vegdistmod', lon1, lat1, lon2, lat2)
}

findcoord <- function(lon, lat, dist, brng) {
    .Call('_vegdistmod_findcoord', PACKAGE = 'vegdistmod', lon, lat, dist, brng)
}

