# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance <- function(start, end) {
    .Call('_vegdistmod_distance', PACKAGE = 'vegdistmod', start, end)
}

findcoord <- function(lon, lat, dist, brng) {
    .Call('_vegdistmod_findcoord', PACKAGE = 'vegdistmod', lon, lat, dist, brng)
}

latlonfromcell <- function(cells, extent, nrow, ncol) {
    .Call('_vegdistmod_latlonfromcell', PACKAGE = 'vegdistmod', cells, extent, nrow, ncol)
}

